// Code generated by "cue exp gengotypes"; DO NOT EDIT.

package linuxcontainers

import (
	"github.com/meigma/go-simplestreams/schema"
)

// ProductFile is the shared Linux Containers image server profile.
type ProductFile struct {
	Format schema.ProductsFormat `json:"format"`

	ContentID string `json:"content_id"`

	DataType string `json:"datatype"`

	Updated schema.Timestamp `json:"updated,omitempty"`

	Products map[string]Product `json:"products"`
}

// Product describes shared Incus/LXD image product metadata.
type Product struct {
	Aliases string `json:"aliases"`

	Arch string `json:"arch"`

	Distro string `json:"distro,omitempty"`

	OS string `json:"os"`

	Release string `json:"release"`

	ReleaseTitle string `json:"release_title"`

	Variant string `json:"variant"`

	Requirements Requirements `json:"requirements"`

	Versions map[string]Version `json:"versions"`
}

// Requirements allows the broader current Linux Containers requirement vocabulary.
type Requirements struct {
	Cgroup string `json:"cgroup,omitempty"`

	SecureBoot StringBool `json:"secureboot,omitempty"`

	CDROMAgent StringBool `json:"cdrom_agent,omitempty"`

	CDROMCloudInit StringBool `json:"cdrom_cloud_init,omitempty"`
}

// StringBool is a boolean encoded as a JSON string, matching current image streams.
type StringBool string

// Version describes one image build.
type Version struct {
	Items map[string]Item `json:"items"`
}

// Item describes shared Linux Containers image artifacts.
type Item struct {
	FileType FileType `json:"ftype"`

	Path schema.RelativePath `json:"path"`

	Size schema.Size `json:"size"`

	SHA256 schema.Checksum `json:"sha256"`

	DeltaBase string `json:"delta_base,omitempty"`

	CombinedSHA256 schema.Checksum `json:"combined_sha256,omitempty"`

	CombinedRootXZSHA256 schema.Checksum `json:"combined_rootxz_sha256,omitempty"`

	CombinedSquashfsSHA256 schema.Checksum `json:"combined_squashfs_sha256,omitempty"`

	CombinedDiskKVMImageSHA256 schema.Checksum `json:"combined_disk-kvm-img_sha256,omitempty"`
}

// FileType is the artifact vocabulary shared by current Incus and LXD streams.
type FileType string

// IncusFileType is the current Incus/Linux Containers artifact vocabulary.
type IncusFileType string

// LXDFileType is the current Canonical LXD artifact vocabulary.
type LXDFileType string
