// Code generated by "cue exp gengotypes"; DO NOT EDIT.

package incus

import (
	"github.com/meigma/go-simplestreams/schema"
	"github.com/meigma/go-simplestreams/schema/linuxcontainers"
)

// ProductFile is the Incus/Linux Containers image server profile.
type ProductFile struct {
	Format schema.ProductsFormat `json:"format"`

	ContentID string `json:"content_id"`

	DataType string `json:"datatype"`

	Updated schema.Timestamp `json:"updated,omitempty"`

	Products map[string]Product `json:"products"`
}

// Product describes Incus/Linux Containers image product metadata.
type Product struct {
	Aliases string `json:"aliases"`

	Arch string `json:"arch"`

	OS string `json:"os"`

	Release string `json:"release"`

	ReleaseTitle string `json:"release_title"`

	Variant string `json:"variant"`

	Requirements Requirements `json:"requirements"`

	Versions map[string]Version `json:"versions"`
}

// Requirements allows the current Incus/Linux Containers requirement vocabulary.
type Requirements struct {
	Cgroup string `json:"cgroup,omitempty"`

	SecureBoot linuxcontainers.StringBool `json:"secureboot,omitempty"`

	CDROMAgent linuxcontainers.StringBool `json:"cdrom_agent,omitempty"`

	CDROMCloudInit linuxcontainers.StringBool `json:"cdrom_cloud_init,omitempty"`
}

// Version describes one Incus/Linux Containers image build.
type Version struct {
	Items map[string]Item `json:"items"`
}

// Item describes Incus/Linux Containers image artifacts.
type Item struct {
	FileType linuxcontainers.IncusFileType `json:"ftype"`

	Path schema.RelativePath `json:"path"`

	Size schema.Size `json:"size"`

	SHA256 schema.Checksum `json:"sha256"`

	DeltaBase string `json:"delta_base,omitempty"`

	CombinedSHA256 schema.Checksum `json:"combined_sha256,omitempty"`

	CombinedRootXZSHA256 schema.Checksum `json:"combined_rootxz_sha256,omitempty"`

	CombinedSquashfsSHA256 schema.Checksum `json:"combined_squashfs_sha256,omitempty"`

	CombinedDiskKVMImageSHA256 schema.Checksum `json:"combined_disk-kvm-img_sha256,omitempty"`
}
