// Code generated by "cue exp gengotypes"; DO NOT EDIT.

package schema

// IndexFile is a Simple Streams index document.
type IndexFile struct {
	// Format identifies this document as a Simple Streams index.
	Format IndexFormat `json:"format"`

	// Updated is the timestamp for the index document.
	Updated Timestamp `json:"updated,omitempty"`

	// Index maps content IDs to product documents or nested indexes.
	Index map[string]IndexEntry `json:"index"`
}

// IndexFormat is the format marker for a Simple Streams index document.
type IndexFormat string

// Timestamp is a Simple Streams timestamp string.
type Timestamp string

// IndexEntry describes one entry in a Simple Streams index document.
type IndexEntry struct {
	// Format identifies the referenced document format when provided.
	Format DocumentFormat `json:"format,omitempty"`

	// DataType describes the referenced content domain when provided.
	DataType DataType `json:"datatype,omitempty"`

	// Path is the stream-root-relative path to the referenced document.
	Path MetadataPath `json:"path"`

	// Updated is the timestamp for the referenced document.
	Updated Timestamp `json:"updated,omitempty"`

	// Products lists product names available through the referenced document.
	Products []string `json:"products,omitempty"`
}

// DocumentFormat is any Simple Streams document format marker modeled by this package.
type DocumentFormat string

// DataType describes the kind of content referenced by an index or product document.
type DataType string

// MetadataPath is a Simple Streams metadata path ending in a supported file format.
type MetadataPath string

// ProductFile is a Simple Streams product document.
type ProductFile struct {
	// Format identifies this document as a Simple Streams product document.
	Format ProductsFormat `json:"format"`

	// ContentID identifies this product document.
	ContentID string `json:"content_id"`

	// DataType describes the product content domain when provided.
	DataType DataType `json:"datatype,omitempty"`

	// Updated is the timestamp for the product document.
	Updated Timestamp `json:"updated,omitempty"`

	// Products maps product names to product metadata and versions.
	Products map[string]Product `json:"products"`
}

// ProductsFormat is the format marker for a Simple Streams product document.
type ProductsFormat string

// Product describes one product in a Simple Streams product document.
type Product struct {
	// Versions maps version names to version metadata and items.
	Versions map[string]Version `json:"versions"`
}

// Version describes one product version in a Simple Streams product document.
type Version struct {
	// Items maps item names to item metadata.
	Items map[string]Item `json:"items"`
}

// Item describes one item in a Simple Streams product version.
type Item struct {
	// FileType identifies the item file type when provided.
	FileType string `json:"ftype,omitempty"`

	// Path is the stream-root-relative path to the artifact when provided.
	Path RelativePath `json:"path,omitempty"`

	// Size is the declared byte size of the artifact when provided.
	Size Size `json:"size,omitempty"`

	// MD5 is the artifact MD5 checksum when provided.
	MD5 Checksum `json:"md5,omitempty"`

	// SHA256 is the artifact SHA-256 checksum when provided.
	SHA256 Checksum `json:"sha256,omitempty"`

	// SHA512 is the artifact SHA-512 checksum when provided.
	SHA512 Checksum `json:"sha512,omitempty"`

	// Mirrors lists alternate mirror prefixes for the artifact path.
	Mirrors []Mirror `json:"mirrors,omitempty"`
}

// Size is the declared byte size of an artifact item.
type Size int64

// Checksum is an artifact checksum value.
type Checksum string

// Mirror is an alternate mirror prefix for an item path.
type Mirror string

// RelativePath is a Simple Streams path relative to a stream root.
type RelativePath string
