// Code generated by "cue exp gengotypes"; DO NOT EDIT.

package lxd

import (
	"github.com/meigma/go-simplestreams/schema"
	"github.com/meigma/go-simplestreams/schema/linuxcontainers"
)

// ProductFile is the Canonical LXD image server profile.
type ProductFile struct {
	Format schema.ProductsFormat `json:"format"`

	ContentID string `json:"content_id"`

	DataType string `json:"datatype"`

	Updated schema.Timestamp `json:"updated,omitempty"`

	Products map[string]Product `json:"products"`
}

// Product describes Canonical LXD image product metadata.
type Product struct {
	Aliases string `json:"aliases"`

	Arch string `json:"arch"`

	Distro string `json:"distro"`

	OS string `json:"os"`

	Release string `json:"release"`

	ReleaseTitle string `json:"release_title"`

	Variant string `json:"variant"`

	Requirements Requirements `json:"requirements"`

	Versions map[string]Version `json:"versions"`
}

// Requirements allows the narrower current Canonical LXD requirement vocabulary.
type Requirements struct {
	Cgroup string `json:"cgroup,omitempty"`

	SecureBoot linuxcontainers.StringBool `json:"secureboot,omitempty"`
}

// Version describes one Canonical LXD image build.
type Version struct {
	Items map[string]Item `json:"items"`
}

// Item describes Canonical LXD image artifacts.
type Item struct {
	FileType linuxcontainers.LXDFileType `json:"ftype"`

	Path schema.RelativePath `json:"path"`

	Size schema.Size `json:"size"`

	SHA256 schema.Checksum `json:"sha256"`

	DeltaBase string `json:"delta_base,omitempty"`

	CombinedSquashfsSHA256 schema.Checksum `json:"combined_squashfs_sha256,omitempty"`

	CombinedDiskKVMImageSHA256 schema.Checksum `json:"combined_disk-kvm-img_sha256,omitempty"`
}
